# Generated by Django 4.1.7 on 2023-06-30 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_alter_teammodel_league_userfollowteammodel_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userfollowteammodel',
            options={'verbose_name': 'کاربر علاقمند به تیم'},
        ),
    ]
