# Generated by Django 4.1.7 on 2023-05-07 09:41

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='cover_image',
            field=models.ImageField(blank=True, default='accounts/defaults/cover.jpg', null=True, upload_to=accounts.models.user_cover_image_path, verbose_name='عکس کاور'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='profile_image',
            field=models.ImageField(blank=True, default='accounts/defaults/avatar-default.png', null=True, upload_to=accounts.models.user_profile_image_path, verbose_name='عکس پروفایل'),
        ),
    ]
