# Generated by Django 4.1.7 on 2023-06-30 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockmodel',
            name='reason',
            field=models.CharField(choices=[('A', 'گزارش این شناسه کاربری'), ('B', 'گزارش مطالب و دیدگاه\u200cهای این کاربر'), ('C', 'هیچی، فقط با این کاربر حال نمی\u200cکنم'), ('D', 'دلایل دیگری وجود دارد')], default='A', max_length=1),
            preserve_default=False,
        ),
    ]
