# Generated by Django 4.1.7 on 2023-05-10 15:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_usermodel_cover_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='followrequestmodel',
            options={'ordering': ['date'], 'verbose_name': 'درخواست دنبال کردن'},
        ),
        migrations.AddField(
            model_name='usermodel',
            name='is_phone_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='followrequestmodel',
            name='from_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='self_follow_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='followrequestmodel',
            name='to_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='other_follow_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='OTPCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(max_length=6)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otp_code', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
