# Generated by Django 4.1.7 on 2023-05-20 12:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_followrequestmodel_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otpcode',
            name='id',
        ),
        migrations.AlterField(
            model_name='otpcode',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='otp_code', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
