# Generated by Django 4.1.7 on 2023-05-20 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_otpcode_id_alter_otpcode_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OTPCode',
            new_name='OTPCodeModel',
        ),
    ]
