# Generated by Django 4.1.7 on 2023-04-24 10:19

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_options_alter_user_about_me_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, default='defaults/avatar-default.png', null=True, upload_to=accounts.models.user_profile_image_path, verbose_name='عکس پروفایل'),
        ),
    ]
