# Generated by Django 4.1.7 on 2023-05-20 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_otpcode_otpcodemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpcodemodel',
            name='code',
            field=models.CharField(max_length=6),
        ),
    ]
