# Generated by Django 4.1.7 on 2023-04-25 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_followmodel'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='followmodel',
            constraint=models.CheckConstraint(check=models.Q(('from_user', models.F('to_user')), _negated=True), name='any_one_cant_follows_it_self'),
        ),
    ]
